Table users {
 id integer [primary key]
 name varchar
 email varchar
 password varchar
}

Table players {
 id integer [primary key]
 name varchar
 profilePic varchar
 team varchar
 positionId integer [ref: > positions.id]
 height varchar
 espnId varchar
}

Table positions {
 id integer [primary key]
 name varchar
}

Table stats {
 id integer [primary key]
 name varchar
}

Table positionStats {
 id integer [primary key]
 statId integer [ref: > stats.id]
 positionId integer [ref: > positions.id]
}

Table picks {
 id integer [primary key]
 userId integer [ref: > users.id]
 statId integer [ref: > stats.id]
 playerId integer [ref: > players.id]
 predictedValue decimal
 isOver boolean
 predictedPercentage integer
}

Table parlays {
 id integer [primary key]
 userId integer [ref: > users.id]
 predictedPercentage integer
 pickIds integer[]
}

Table tails {
 id integer [primary key]
 userId integer [ref: > users.id]
 pickId integer [ref: > picks.id]
}

Ref: parlays.pickIds > picks.id
Ref: stats.id < positionStats.statId
Ref: positions.id < positionStats.positionId
Ref: positions.id < players.positionId
Ref: users.id < picks.userId
Ref: stats.id < picks.statId
Ref: players.id < picks.playerId
Ref: users.id < parlays.userId
Ref: users.id < tails.userId
Ref: picks.id < tails.pickId