Table players {
 id integer [primary key]
 name varchar
 profilePic varchar
 team varchar
 positionId integer [ref: > positions.id]
 height varchar
 espnId varchar
}

Table positions {
 id integer [primary key]
 name varchar
}

Table stats {
 id integer [primary key]
 name varchar
}

Table positionStats {
 id integer [primary key]
 statId integer [ref: > stats.id]
 positionId integer [ref: > positions.id]
}

Table users {
 id integer [primary key]
 name varchar
 email varchar
 password varchar
}

Table picks {
 id integer [primary key]
 userId integer [ref: > users.id]
 statId integer [ref: > stats.id]
 playerId integer [ref: > players.id]
 predictedValue decimal
 isOver boolean
 predictedPercentage integer
}

Table parlays {
 id integer [primary key]
 userId integer [ref: > users.id]
 predictedPercentage integer
 pickIds integer[] 
}

Table tails {
 id integer [primary key]  
 userId integer [ref: > users.id]
 pickId integer [ref: > picks.id]
}

Table parlayTails {
 id integer [primary key]
 userId integer [ref: > users.id]
 parlayId integer [ref: > parlays.id]
}